---
abstract: 'I know numeric methods'
author:
  - 'Kang-min Liu <gugod@gugod.org>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'App::ModuleBuildTiny version 0.027, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Acme-NumericMethod
provides:
  Acme::NumericMethod:
    file: lib/Acme/NumericMethod.pm
    version: '0.05'
requires:
  Lingua::EN::Words2Nums: '0'
resources:
  bugtracker: https://github.com/gugod/Acme-NumericMethod/issues
  repository: https://github.com/gugod/Acme-NumericMethod.git
version: '0.05'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
x_static_install: '1'
